---
language: java
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
  - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
before_install:
- unset GEM_PATH
script:
- sudo ln -s /usr/bin/md5sum /usr/bin/md5
- mvn clean install -Pqulice --batch-mode --errors
